# File: azure-template-docker-job.yml
# Date: 22-Aug-2020 jdw Preliminary version
#
# Updates:
#
##
parameters:
  os: ""
  docker_task: ""

jobs:
- job: ${{ format('build_docker_{0}_{1}', parameters.docker_task, parameters.os) }}
  timeoutInMinutes: 0
  pool:
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-18.04'

  variables:
  - template: azure-template-variables.yml
