# File: azure-template-docker-job.yml
# Date: 22-Aug-2020 jdw Preliminary version
#
# Updates:
#
##
parameters:
  os: ""
  docker_task: ""

jobs:
- job: ${{ format('build_docker_{0}_{1}', parameters.docker_task, parameters.os) }}
  timeoutInMinutes: 0
  pool:
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: 'ubuntu-18.04'

    dependsOn:
    - ${{ format('build_docker_{0}_{1}', parameters.docker_task, parameters.os) }}
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

  variables:
  - template: azure-template-variables.yml

  steps:
  - bash: echo "variables - py_module ${{variables.py_module}} image_name ${{variables.image_name}} registry_user ${{variables.registry_user}} "
  - bash: echo "parameters - docker_task ${{parameters.docker_task}} os ${{parameters.os}}"
  #
  - checkout: self
    submodules: true
  #
  - task: DockerInstaller@0
    displayName: "Docker Installer"
    inputs:
        #dockerVersion: 17.09.0-ce
        dockerVersion: 19.03.9
        releaseType: stable
  #
  - task: Docker@2
    displayName: "Login to DockerHub"
    inputs:
        command: login
        containerRegistry: dockerhubtest
  #
  - bash: echo "DONE"